package com.abietic.ap1.mapper;

import com.abietic.ap1.model.StockLog;
import org.apache.ibatis.jdbc.SQL;

public class StockLogSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 31 13:16:33 UTC 2022
     */
    public String insertSelective(StockLog row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("stock_log");
        
        if (row.getStockLogId() != null) {
            sql.VALUES("stock_log_id", "#{stockLogId,jdbcType=VARCHAR}");
        }
        
        if (row.getItemId() != null) {
            sql.VALUES("item_id", "#{itemId,jdbcType=INTEGER}");
        }
        
        if (row.getAmount() != null) {
            sql.VALUES("amount", "#{amount,jdbcType=INTEGER}");
        }
        
        if (row.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 31 13:16:33 UTC 2022
     */
    public String updateByPrimaryKeySelective(StockLog row) {
        SQL sql = new SQL();
        sql.UPDATE("stock_log");
        
        if (row.getItemId() != null) {
            sql.SET("item_id = #{itemId,jdbcType=INTEGER}");
        }
        
        if (row.getAmount() != null) {
            sql.SET("amount = #{amount,jdbcType=INTEGER}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        sql.WHERE("stock_log_id = #{stockLogId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}