package com.abietic.ap1.mapper;

import com.abietic.ap1.model.UserPassword;
import org.apache.ibatis.jdbc.SQL;

public class UserPasswordSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String insertSelective(UserPassword row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_password");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (row.getEncrptPassword() != null) {
            sql.VALUES("encrpt_password", "#{encrptPassword,jdbcType=VARCHAR}");
        }
        
        if (row.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String updateByPrimaryKeySelective(UserPassword row) {
        SQL sql = new SQL();
        sql.UPDATE("user_password");
        
        if (row.getEncrptPassword() != null) {
            sql.SET("encrpt_password = #{encrptPassword,jdbcType=VARCHAR}");
        }
        
        if (row.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}