package com.abietic.ap1.mapper;

import com.abietic.ap1.model.ItemStock;
import org.apache.ibatis.jdbc.SQL;

public class ItemStockSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String insertSelective(ItemStock row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("item_stock");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (row.getStock() != null) {
            sql.VALUES("stock", "#{stock,jdbcType=INTEGER}");
        }
        
        if (row.getItemId() != null) {
            sql.VALUES("item_id", "#{itemId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String updateByPrimaryKeySelective(ItemStock row) {
        SQL sql = new SQL();
        sql.UPDATE("item_stock");
        
        if (row.getStock() != null) {
            sql.SET("stock = #{stock,jdbcType=INTEGER}");
        }
        
        if (row.getItemId() != null) {
            sql.SET("item_id = #{itemId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}