package com.abietic.ap1.mapper;

import com.abietic.ap1.model.Order;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    @Delete({
        "delete from order_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    @Insert({
        "insert into order_info (id, user_id, ",
        "item_id, item_price, ",
        "amount, order_price, ",
        "promo_id)",
        "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER}, ",
        "#{itemId,jdbcType=INTEGER}, #{itemPrice,jdbcType=DOUBLE}, ",
        "#{amount,jdbcType=INTEGER}, #{orderPrice,jdbcType=DOUBLE}, ",
        "#{promoId,jdbcType=INTEGER})"
    })
    int insert(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    @InsertProvider(type=OrderSqlProvider.class, method="insertSelective")
    int insertSelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    @Select({
        "select",
        "id, user_id, item_id, item_price, amount, order_price, promo_id",
        "from order_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.INTEGER),
        @Result(column="item_price", property="itemPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER),
        @Result(column="order_price", property="orderPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="promo_id", property="promoId", jdbcType=JdbcType.INTEGER)
    })
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    @Update({
        "update order_info",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "item_id = #{itemId,jdbcType=INTEGER},",
          "item_price = #{itemPrice,jdbcType=DOUBLE},",
          "amount = #{amount,jdbcType=INTEGER},",
          "order_price = #{orderPrice,jdbcType=DOUBLE},",
          "promo_id = #{promoId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order row);
}