package com.abietic.ap1.mapper;

import com.abietic.ap1.model.Promo;
import org.apache.ibatis.jdbc.SQL;

public class PromoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String insertSelective(Promo row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("promo");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (row.getPromoName() != null) {
            sql.VALUES("promo_name", "#{promoName,jdbcType=VARCHAR}");
        }
        
        if (row.getStartDate() != null) {
            sql.VALUES("start_date", "#{startDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getEndDate() != null) {
            sql.VALUES("end_date", "#{endDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getItemId() != null) {
            sql.VALUES("item_id", "#{itemId,jdbcType=INTEGER}");
        }
        
        if (row.getPromoItemPrice() != null) {
            sql.VALUES("promo_item_price", "#{promoItemPrice,jdbcType=DOUBLE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String updateByPrimaryKeySelective(Promo row) {
        SQL sql = new SQL();
        sql.UPDATE("promo");
        
        if (row.getPromoName() != null) {
            sql.SET("promo_name = #{promoName,jdbcType=VARCHAR}");
        }
        
        if (row.getStartDate() != null) {
            sql.SET("start_date = #{startDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getEndDate() != null) {
            sql.SET("end_date = #{endDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getItemId() != null) {
            sql.SET("item_id = #{itemId,jdbcType=INTEGER}");
        }
        
        if (row.getPromoItemPrice() != null) {
            sql.SET("promo_item_price = #{promoItemPrice,jdbcType=DOUBLE}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}