package com.abietic.ap1.mapper;

import com.abietic.ap1.model.User;
import org.apache.ibatis.jdbc.SQL;

public class UserSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String insertSelective(User row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_info");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (row.getGender() != null) {
            sql.VALUES("gender", "#{gender,jdbcType=TINYINT}");
        }
        
        if (row.getAge() != null) {
            sql.VALUES("age", "#{age,jdbcType=INTEGER}");
        }
        
        if (row.getTelphone() != null) {
            sql.VALUES("telphone", "#{telphone,jdbcType=VARCHAR}");
        }
        
        if (row.getRegisterMode() != null) {
            sql.VALUES("register_mode", "#{registerMode,jdbcType=VARCHAR}");
        }
        
        if (row.getThirdPartyId() != null) {
            sql.VALUES("third_party_id", "#{thirdPartyId,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 15 15:39:34 UTC 2022
     */
    public String updateByPrimaryKeySelective(User row) {
        SQL sql = new SQL();
        sql.UPDATE("user_info");
        
        if (row.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (row.getGender() != null) {
            sql.SET("gender = #{gender,jdbcType=TINYINT}");
        }
        
        if (row.getAge() != null) {
            sql.SET("age = #{age,jdbcType=INTEGER}");
        }
        
        if (row.getTelphone() != null) {
            sql.SET("telphone = #{telphone,jdbcType=VARCHAR}");
        }
        
        if (row.getRegisterMode() != null) {
            sql.SET("register_mode = #{registerMode,jdbcType=VARCHAR}");
        }
        
        if (row.getThirdPartyId() != null) {
            sql.SET("third_party_id = #{thirdPartyId,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}