# Use root/example as user/password credentials
version: '3.1'

networks:
  front-tier:
    # driver: overlay
    attachable: true
  back-tier:
    # driver: overlay
    attachable: true
  cluster-redis-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

services:
  server-and-proxy:
    image: nginx:1.16
    volumes:
      - "./nginx:/etc/nginx:ro" # :ro stands for read-only
      - "./pages:/app"
    ports:
      - 80:80
      - 443:443
    depends_on:
      # - spring-app
      - adminer
    networks:
      - front-tier
    command: [nginx]
    # command: [nginx-debug, '-g', 'daemon off;']

  db:
    image: mysql:5.7
    # 这个命令保证了数据库使用最长4bytes的UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      # - MYSQL_USER=admin
      # - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=ap1
    volumes:
      # 这一条是初始化要使用的数据库和表用的
      # - "./mysql/db_test_entry:/docker-entrypoint-initdb.d"
      # 这条是生成的数据库文件存放的位置
      - "./mysql/db_data_dir:/var/lib/mysql"
      # 这个是设置数据库的配置文件，这时只设置了使用最长4bytes的UTF-8
      - "./mysql/db_config:/etc/mysql/conf.d"
    networks:
      back-tier:
        aliases:
          - database

  spring-app:
    # image: maven:3-openjdk-8
    image: maven:3-jdk-11 # 如果用下面版本的image会导致生成验证码的模块找不到对应的font
    # image: adoptopenjdk/openjdk11:alpine-slim
    working_dir: /app
    volumes:
      - "./spring-app:/app"
      - "~/.m2:/root/.m2"
    depends_on:
      - db
      - rocketmq-broker
      # - cache-redis 
      # - session-redis
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      front-tier:
        aliases:
          - webapp
      back-tier:
      cluster-redis-net:
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=\"-Xmx512m\""]
    # command: ["./mvnw", "spring-boot:run", "-Dreactor.netty.http.server.accessLogEnabled=true"]
    # command: ["./mvnw", "mybatis-generator:generate"]

  # 服务端程序负载均衡的添加程序
  spring-app-copy:
    # image: maven:3-openjdk-8
    image: maven:3-jdk-11 # 如果用下面版本的image会导致生成验证码的模块找不到对应的font
    # image: adoptopenjdk/openjdk11:alpine-slim
    working_dir: /app
    volumes:
      - "./spring-app:/app"
      - "~/.m2:/root/.m2"
    depends_on:
      - db
      - rocketmq-broker
      # - session-redis
      # - cache-redis 
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

    networks:
      front-tier:
        aliases:
          - webapp-copy
      back-tier:
      cluster-redis-net:
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=\"-Xmx512m\""]
    # command: ["./mvnw", "spring-boot:run", "-Dreactor.netty.http.server.accessLogEnabled=true"]
    # command: ["./mvnw", "mybatis-generator:generate"]


  rocketmq-namesrv:
    image: rocketmqinc/rocketmq
    # ports:
    #   - "9876:9876"
    volumes:
      - "./rocketmq/logs:/home/rocketmq/logs"
      - "./rocketmq/store:/home/rocketmq/store"
    networks:
      back-tier:
        aliases:
          - rocketmq-namesrv
    command: ["sh", "mqnamesrv"]
    environment:
      - MAX_POSSIBLE_HEAP=268435456



  rocketmq-broker:
    image: rocketmqinc/rocketmq
    # ports:
    #   - "10909:10909"
    #   - "10911:10911"
    #   - "10912:10912"
    volumes:
      - "./rocketmq/logs:/home/rocketmq/logs"
      - "./rocketmq/store:/home/rocketmq/store"
      - "./rocketmq/broker-conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf"
    networks:
      back-tier:
        aliases:
          - rocketmq-broker
    command: ["sh", "mqbroker", "-n", "rocketmq-namesrv:9876", "-c", "../conf/broker.conf"]
    depends_on:
      - rocketmq-namesrv
    environment:
      # 最大最大堆大小设置为512m
      # - MAX_POSSIBLE_HEAP=536870912
      # 最大最大堆大小设置为256m
      - MAX_POSSIBLE_HEAP=268435456


  rocketmq-console-ng:
    image: styletang/rocketmq-console-ng
    ports:
      - 8087:8080
    depends_on:
      - rocketmq-namesrv
    networks:
      back-tier:
        aliases:
          - rocketmq-console-ng
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rocketmq-namesrv:9876 
      - Dcom.rocketmq.sendMessageWithVIPChannel=false
    

  cas-server:
    # image: org.apereo.cas/cas:6.1.5
    image: apereo/cas:v6.5.8
    # ports:
    #   - "8089:8089"
    # volumes:
    #   - "./cas-server/cas-overlay-template-6.5/etc/cas/config:/etc/cas/config"
    #   - "./cas-server/cas-overlay-template-6.5/etc/cas/services:/etc/cas/services"
    depends_on:
      - db
    networks:
      front-tier:
        aliases:
          - cas-server
      back-tier:

  
  adminer:
    image: adminer
    depends_on:
      - db
    networks:
      front-tier:
        aliases:
          - dblooker
      back-tier:

# 如果构建后还未设置redis cluster需要运行命令构成cluster
# redis-cli -a 123456 --cluster create 173.17.0.2:6379 173.17.0.3:6379 173.17.0.4:6379 \
# 173.17.0.5:6379 173.17.0.6:6379 173.17.0.7:6379 \
# --cluster-replicas 1

  redis-1:
    image: redis:5
    volumes:
      - "./redis/redis-cluster/redis-1-data:/data"
      - "./redis/redis-cluster/redis.conf:/etc/redis/redis.conf"
    networks:
      cluster-redis-net:
        ipv4_address: 173.17.0.2
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  redis-2:
    image: redis:5
    volumes:
      - "./redis/redis-cluster/redis-2-data:/data"
      - "./redis/redis-cluster/redis.conf:/etc/redis/redis.conf"
    networks:
      cluster-redis-net:
        ipv4_address: 173.17.0.3
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  redis-3:
    image: redis:5
    volumes:
      - "./redis/redis-cluster/redis-3-data:/data"
      - "./redis/redis-cluster/redis.conf:/etc/redis/redis.conf"
    networks:
      cluster-redis-net:
        ipv4_address: 173.17.0.4
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  redis-4:
    image: redis:5
    volumes:
      - "./redis/redis-cluster/redis-4-data:/data"
      - "./redis/redis-cluster/redis.conf:/etc/redis/redis.conf"
    networks:
      cluster-redis-net:
        ipv4_address: 173.17.0.5
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  redis-5:
    image: redis:5
    volumes:
      - "./redis/redis-cluster/redis-5-data:/data"
      - "./redis/redis-cluster/redis.conf:/etc/redis/redis.conf"
    networks:
      cluster-redis-net:
        ipv4_address: 173.17.0.6
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  redis-6:
    image: redis:5
    volumes:
      - "./redis/redis-cluster/redis-6-data:/data"
      - "./redis/redis-cluster/redis.conf:/etc/redis/redis.conf"
    networks:
      cluster-redis-net:
        ipv4_address: 173.17.0.7
    command: [ "redis-server", "/etc/redis/redis.conf" ]


  # session-redis:
  #   image: redis:5
  #   # ports:
  #   #   - "6379:6379"
  #   volumes:
  #     - "./redis/session-data:/data"
  #     - "./redis/session-conf/redis.conf:/etc/redis/redis.conf"
  #   # depends_on:
  #   #   - db
  #   networks:
  #     back-tier:
  #       aliases:
  #         - session-redis
  #     cluster-redis-net:
  #   command: [ "redis-server", "/etc/redis/redis.conf" ]

  # cache-redis:
  #   image: redis:5
  #   # ports:
  #   #   - "6379:6379"
  #   volumes:
  #     - "./redis/cache-data:/data"
  #     - "./redis/cache-conf/redis.conf:/etc/redis/redis.conf"
  #   # depends_on:
  #   #   - db
  #   networks:
  #     back-tier:
  #       aliases:
  #         - cache-redis
  #     cluster-redis-net:
  #   command: [ "redis-server", "/etc/redis/redis.conf" ]
