server:
  port: 8088
  tomcat:
    accept-count: 1000
    threads: 
      max: 800
      min: 100
mybatis:
  # mapper-locations: classpath:mapper/*.xml
  configuration: 
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rocketmq:
  name-server: rocketmq-namesrv:9876
  topic: stock
  producer:
    group: my-group
spring:
  session:
    store-type: redis
    # timeout: 30m # 对应1800s maxInteractiveInterval
    timeout: 60m # 对应3600s maxInteractiveInterval
    redis:
      flush-mode: on_save # 在进行response后才进行同步
      # flush-mode: immediate # 在setAttribute后立刻进行同步
      namespace: spring:session
  # redis:
  #   host: session-redis
  #   password: foobared
  #   port: 6379
  session-redis:
    host: session-redis
    password: foobared
    port: 6379
  cache-redis:
    host: cache-redis
    password: 123456
    port: 6379
  token-redis:
    host: token-redis
    password: 123456
    port: 6379
  
  datasource:
    # name: seckill
    url: jdbc:mysql://database:3306/ap1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    #使用 druid 数据源
    # type: com.alibaba.druid.pool.DruidDataSource
    # driver-class-name: com.mysql.cj.jdbc.Driver
    